"""Add UserPreferences model

Revision ID: 0f62fc3916ac
Revises: aa8b015e481e
Create Date: 2024-07-25 10:22:07.076836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f62fc3916ac'
down_revision = 'aa8b015e481e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_range', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('preferred_brands', sa.PickleType(), nullable=True),
    sa.Column('usage', sa.String(length=50), nullable=True),
    sa.Column('daily_commute', sa.Float(), nullable=True),
    sa.Column('fast_charging_max_time', sa.Float(), nullable=True),
    sa.Column('manufacturing_country', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
