"""Add usage column to Car table

Revision ID: 8df93bd4d760
Revises: 2b67737c6d36
Create Date: 2024-07-24 20:35:37.089228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df93bd4d760'
down_revision = '2b67737c6d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('usage')

    # ### end Alembic commands ###
