"""Add daily_commute column to Car table

Revision ID: aa8b015e481e
Revises: a14fad792ebd
Create Date: 2024-07-24 22:30:27.240221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8b015e481e'
down_revision = 'a14fad792ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_commute', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('daily_commute')

    # ### end Alembic commands ###
